#=== Directories ===#
real_data_path: /afhq
syn_data_path: /sd
save_path: /models

#=== Data Param ===#
batch_size: 128
img_size: 224

#=== Training Param ===#
model_name: nn_afhq 
num_epochs: 30
lr: 0.0001
beta_1: 0.9
beta_2:  0.999
weight_decay: 0.001 
early_stopping: yes
tolerance: 5
min_delta: 0
seed: [1, 28, 42, 54, 76]