#=== Directories ===#
data_path: ./sd/
save_path: ./models/
save_plot: ./plot/

#=== Data Param ===#
batch_size: 128
img_size: 224

#=== Training Param ===#
model: nn_sd
num_epochs: 30
learning_rate: 0.0001
beta_1: 0.9
beta_2:  0.999
weight_decay: 0.001
loss: BCE 
early_stopping: yes
tolerance: 5
min_delta: 0
seed: [1, 28, 42, 54, 76]